// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy8jXQLucYrOq7xzxmB7KY8HXyLuk4kL0',
    appId: '1:194118551352:web:1ae7e9db876053af63a3cd',
    messagingSenderId: '194118551352',
    projectId: 'pethouse-v1',
    authDomain: 'pethouse-v1.firebaseapp.com',
    storageBucket: 'pethouse-v1.firebasestorage.app',
    measurementId: 'G-DB2EEGB5T5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrn8y8zNXmezqghTjfvIuopgVuViSEUIo',
    appId: '1:194118551352:android:f32c43bcfa92797e63a3cd',
    messagingSenderId: '194118551352',
    projectId: 'pethouse-v1',
    storageBucket: 'pethouse-v1.firebasestorage.app',
  );

}